# Generated by Django 3.0.3 on 2020-02-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_expert_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header_weight', models.IntegerField()),
                ('header_text', models.CharField(max_length=255)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
        ),
    ]
