# Generated by Django 3.0.3 on 2020-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Finished')], default=1),
            preserve_default=False,
        ),
    ]
