# Generated by Django 3.0.3 on 2020-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='task_id',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
